
import { Fruit, FruitGroup, BlessingType } from './types';

export const FRUITS: Fruit[] = [
  {
    id: 'wheat',
    name: 'חיטה',
    scientificName: 'Triticum',
    group: FruitGroup.SevenSpecies,
    blessing: BlessingType.Mezonot,
    canEatRaw: false,
    hasPit: false,
    pitDescription: 'ללא גלעין',
    hasPeel: true,
    peelEdible: false,
    priorityOrder: 1,
    description: 'הראשונה ב**שבעת המינים**. משמשת להכנת **לחם ומאפים**. החיטה מסמלת בתרבות היהודית את הכלכלה הבסיסית וחיונית לתזונה.',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?q=80&w=1200',
    varietiesCount: 30000,
    famousVarieties: ['חיטת הלחם', 'חיטת דורום', 'גליל', 'רותם'],
    seasonality: 'חורף-אביב (קציר באייר-סיון)'
  },
  {
    id: 'barley',
    name: 'שעורה',
    scientificName: 'Hordeum vulgare',
    group: FruitGroup.SevenSpecies,
    blessing: BlessingType.Mezonot,
    canEatRaw: false,
    hasPit: false,
    pitDescription: 'ללא גלעין',
    hasPeel: true,
    peelEdible: false,
    priorityOrder: 2,
    description: 'השנייה ב**שבעת המינים**. משמשת לייצור **בירה ומזון לבהמות**. נחשבת לגידול עמיד מאוד לתנאי אקלים קשים.',
    image: 'https://images.unsplash.com/photo-1536511132770-e5066804d960?q=80&w=1200',
    varietiesCount: 2500,
    famousVarieties: ['שעורה דו-טורית', 'שעורה שש-טורית', 'עומר'],
    seasonality: 'חורף-אביב (קציר מוקדם מהחיטה)'
  },
  {
    id: 'apple',
    name: 'תפוח',
    scientificName: 'Malus domestica',
    group: FruitGroup.StoneFruit,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'מספר גרעינים קטנים ושחורים המרוכזים בתוך ליבת הפרי.',
    hasPeel: true,
    peelEdible: true,
    description: 'ה**תפוח** הוא אחד הפירות הפופולריים בעולם. בישראל מגדלים זנים מעולים בעיקר באזור הגליל והגולן.',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6bcd6?q=80&w=1200',
    varietiesCount: 7500,
    famousVarieties: ['פינק ליידי', 'אנה (פיתוח ישראלי)', 'גרני סמית', 'גאלה', 'יונתן'],
    seasonality: 'קיץ-סתיו (זמין כל השנה בקירור)'
  },
  {
    id: 'banana',
    name: 'בננה',
    scientificName: 'Musa',
    group: FruitGroup.Tropical,
    blessing: BlessingType.Adama,
    canEatRaw: true,
    hasPit: false,
    pitDescription: 'ללא גלעינים משמעותיים (הנקודות השחורות הקטנות הן שרידי זרעים).',
    hasPeel: true,
    peelEdible: false,
    description: 'ה**בננה** גדלה בישראל בעיקר בבקעת הירדן ובחוף הכרמל. למרות המראה העצי, מבחינה בוטנית היא נחשבת לעשב.',
    image: 'https://images.unsplash.com/photo-1571771894821-ad99026a09b7?q=80&w=1200',
    varietiesCount: 1000,
    famousVarieties: ['קוונדיש (זיו)', 'בננה ננסית', 'פלאנטיין'],
    seasonality: 'כל השנה (שיא בחורף)'
  },
  {
    id: 'mango',
    name: 'מנגו',
    scientificName: 'Mangifera indica',
    group: FruitGroup.Tropical,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'גלעין גדול, שטוח וסיבי במרכז הפרי.',
    hasPeel: true,
    peelEdible: false,
    description: 'ה**מנגו הישראלי** נחשב לאיכותי מאוד ומושקה במים המינרליים של אזור הכנרת. פרי מתוק, עסיסי וריחני.',
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?q=80&w=1200',
    varietiesCount: 1000,
    famousVarieties: ["מאיה (הכי פופולרי)", "שלי", "קיט", "טומי אטקינס"],
    seasonality: 'קיץ (יולי-ספטמבר)'
  },
  {
    id: 'watermelon',
    name: 'אבטיח',
    scientificName: 'Citrullus lanatus',
    group: FruitGroup.Melons,
    blessing: BlessingType.Adama,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'מאות גרעינים שחורים או לבנים המפוזרים בתוך הציפה האדומה.',
    hasPeel: true,
    peelEdible: false,
    description: 'ה**אבטיח** הוא מלך הקיץ הישראלי. בישראל פותחו זנים ללא גרעינים שהפכו ללהיט עולמי.',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?q=80&w=1200',
    varietiesCount: 1200,
    famousVarieties: ['מללי (קלאסי)', 'פאשיניישן (ללא גרעינים)', 'אבטיח צהוב'],
    seasonality: 'קיץ (מאי-אוגוסט)'
  },
  {
    id: 'pear',
    name: 'אגס',
    scientificName: 'Pyrus',
    group: FruitGroup.StoneFruit,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'גלעינים קטנים וכהים בתוך ליבת הפרי.',
    hasPeel: true,
    peelEdible: true,
    description: 'ה**אגס** מצטיין במרקם גרגירי עדין וטעם מתוק-חמצמץ. נקטף כשהוא קשה ומבשיל בטמפרטורת החדר.',
    image: 'https://images.unsplash.com/photo-1514756331096-242fdeb70d4a?q=80&w=1200',
    varietiesCount: 3000,
    famousVarieties: ["ספאדונה", "קוסטיה", "ג'נטיל"],
    seasonality: 'קיץ-סתיו'
  },
  {
    id: 'kiwi',
    name: 'קיווי',
    scientificName: 'Actinidia deliciosa',
    group: FruitGroup.Tropical,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'זרעים שחורים זעירים ורבים הנאכלים עם הפרי.',
    hasPeel: true,
    peelEdible: true,
    description: 'ה**קיווי** עשיר מאוד בויטמין C. בישראל הוא גדל היטב באזורים הקרירים יותר.',
    image: 'https://images.unsplash.com/photo-1585052245554-fb677e3f6392?q=80&w=1200',
    varietiesCount: 60,
    famousVarieties: ['היוורד', 'ברונו', 'גולד'],
    seasonality: 'חורף (נובמבר-מרץ)'
  },
  {
    id: 'melon',
    name: 'מלון',
    scientificName: 'Cucumis melo',
    group: FruitGroup.Melons,
    blessing: BlessingType.Adama,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'ריכוז של זרעים בהירים במרכז החלול של הפרי.',
    hasPeel: true,
    peelEdible: false,
    description: 'ה**מלון** הישראלי ידוע במתיקותו הגבוהה. קיימים זנים רבים כמו גליה, קנטלופ ודבש.',
    image: 'https://images.unsplash.com/photo-1571575173749-bef869f82367?q=80&w=1200',
    varietiesCount: 40,
    famousVarieties: ['גליה (פיתוח ישראלי)', 'ערבה', 'קנטלופ', 'מלון דבש'],
    seasonality: 'קיץ'
  },
  {
    id: 'loquat',
    name: 'שסק',
    scientificName: 'Eriobotrya japonica',
    group: FruitGroup.StoneFruit,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: true,
    pitDescription: '2-4 גלעינים חומים גדולים, חלקים ומבריקים במרכז הפרי.',
    hasPeel: true,
    peelEdible: true,
    description: 'ה**שסק** הוא פרי אביב צהוב ומתקתק. בישראל הוא גדל בהצלחה רבה והוא מהראשונים להופיע אחרי החורף.',
    image: 'https://images.unsplash.com/photo-1623112429061-0d33878b4b7c?q=80&w=1200',
    varietiesCount: 800,
    famousVarieties: ['עכו 1', 'עכו 13', 'טאנקה'],
    seasonality: 'אביב (מרץ-מאי)'
  },
  {
    id: 'pomelo',
    name: 'פומלה',
    scientificName: 'Citrus maxima',
    group: FruitGroup.Citrus,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'זרעים לבנים גדולים יחסית, אך בזנים רבים היא כמעט ללא זרעים.',
    hasPeel: true,
    peelEdible: false,
    description: 'ה**פומלה** היא הגדולה מבין פירות ההדר. קליפתה עבה מאוד והיא מצריכה קילוף משמעותי.',
    image: 'https://images.unsplash.com/photo-1592176372045-2199e800a391?q=80&w=1200',
    varietiesCount: 20,
    famousVarieties: ["צ'נדלר", "גוליית", "פומלה לבנה"],
    seasonality: 'חורף (דצמבר-מרץ)'
  },
  {
    id: 'olive',
    name: 'זית',
    scientificName: 'Olea europaea',
    group: FruitGroup.SevenSpecies,
    blessing: BlessingType.Etz,
    canEatRaw: false,
    hasPit: true,
    pitDescription: 'גלעין יחיד, קשיח מאוד, מוארך ומחוספס במרכז הפרי.',
    hasPeel: true,
    peelEdible: true,
    priorityOrder: 3,
    description: 'הראשון בסדר הקדימות של **פירות האילן**. עץ הזית הוא סמל ה**שלום** והפקת השמן ממנו היא מסורת עתיקה.',
    image: 'https://images.unsplash.com/photo-1541530531070-449e7939103c?q=80&w=1200',
    varietiesCount: 2000,
    famousVarieties: ['ברנע (פיתוח ישראלי)', 'סורי', 'נבאלי', 'פיקואל'],
    seasonality: 'סתיו (אוקטובר-נובמבר)'
  },
  {
    id: 'date',
    name: 'תמר',
    scientificName: 'Phoenix dactylifera',
    group: FruitGroup.SevenSpecies,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'גלעין יחיד, קשיח, מוארך עם חריץ עמוק לאורכו.',
    hasPeel: true,
    peelEdible: true,
    priorityOrder: 4,
    description: 'השני בסדר הקדימות. ה**דבש** המוזכר בפסוק כ"ארץ זבת חלב ודבש" מתייחס ל**דבש תמרים** מתוק.',
    image: 'https://images.unsplash.com/photo-1571221715431-7b567a14e101?q=80&w=1200',
    varietiesCount: 3000,
    famousVarieties: ["מג'הול (מלך התמרים)", "חיאני", "ברהי (צהוב)", "דקל נור"],
    seasonality: 'סתיו (ספטמבר-אוקטובר)'
  },
  {
    id: 'grape',
    name: 'ענב',
    scientificName: 'Vitis vinifera',
    group: FruitGroup.SevenSpecies,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'מספר חרצנים קטנים (1-4), בצורת טיפה, קשיחים ומרירים.',
    hasPeel: true,
    peelEdible: true,
    priorityOrder: 5,
    description: 'השלישי בסדר הקדימות. משמש למאכל כ**פרי טרי**, כצימוקים וליצירת **יין ישראלי** משובח.',
    image: 'https://images.unsplash.com/photo-1537640538966-79f369b41e8f?q=80&w=1200',
    varietiesCount: 10000,
    famousVarieties: ['תומפסון', 'סופריור', 'קרימסון', 'מוסקט'],
    seasonality: 'קיץ'
  },
  {
    id: 'fig',
    name: 'תאנה',
    scientificName: 'Ficus carica',
    group: FruitGroup.SevenSpecies,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'מאות גרגירים זעירים (זרעים) פריכים ומתקתקים המפוזרים בבשר הפרי.',
    hasPeel: true,
    peelEdible: true,
    priorityOrder: 6,
    description: 'הרביעית בסדר הקדימות. ה**תאנה** נאכלת טרייה או מיובשת כ**דבלה**. פרי עסיסי ומתוק במיוחד.',
    image: 'https://images.unsplash.com/photo-1582234151325-06a19f2a47f2?q=80&w=1200',
    varietiesCount: 750,
    famousVarieties: ['נצרת', 'ברזילאית', 'ירוקה'],
    seasonality: 'קיץ (יוני-ספטמבר)'
  },
  {
    id: 'pomegranate',
    name: 'רימון',
    scientificName: 'Punica granatum',
    group: FruitGroup.SevenSpecies,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'מאות גרעינים (כ-613), כל אחד עטוף בציפה אדומה ועסיסית.',
    hasPeel: true,
    peelEdible: false,
    priorityOrder: 7,
    description: 'החמישי בסדר הקדימות. ה**רימון** ידוע בסגולותיו הבריאותיות ובסימליות שלו כפרי המלא ב**מצוות וזכויות**.',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?q=80&w=1200',
    varietiesCount: 500,
    famousVarieties: ['וונדרפול', 'עמק', 'עכו'],
    seasonality: 'סתיו (אוגוסט-נובמבר)'
  },
  {
    id: 'avocado',
    name: 'אבוקדו',
    scientificName: 'Persea americana',
    group: FruitGroup.Tropical,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'גלעין אחד ענקי, עגול או אובלי, חלק וחום כהה.',
    hasPeel: true,
    peelEdible: false,
    description: 'ישראל היא מהמובילות בעולם בייצוא **אבוקדו**. פרי עשיר בחומצות שומן בריאות.',
    image: 'https://images.unsplash.com/photo-1523049673857-d11dd310095c?q=80&w=1200',
    varietiesCount: 500,
    famousVarieties: ['האס (Hass)', 'אטינגר (Ettinger)', 'פוארטה (Fuerte)'],
    seasonality: 'חורף-אביב'
  },
  {
    id: 'strawberry',
    name: 'תות שדה',
    scientificName: 'Fragaria',
    group: FruitGroup.Forest,
    blessing: BlessingType.Adama,
    canEatRaw: true,
    hasPit: false,
    pitDescription: 'מאות זרעים זעירים המפוזרים על פני הקליפה החיצונית.',
    hasPeel: false,
    peelEdible: true,
    description: 'ה**תות הישראלי** הוא סמל לחורף. דורש שטיפה יסודית למניעת חרקים.',
    image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?q=80&w=1200',
    varietiesCount: 100,
    famousVarieties: ['אורלי', 'תמר', 'מלאך'],
    seasonality: 'חורף-אביב (דצמבר-מאי)'
  },
  {
    id: 'cherry_tomato',
    name: 'עגבניית שרי',
    scientificName: 'Solanum lycopersicum',
    group: FruitGroup.ExoticVegetables,
    blessing: BlessingType.Adama,
    canEatRaw: true,
    hasPit: false,
    pitDescription: 'זרעים קטנים ורכים הנאכלים עם הפרי.',
    hasPeel: false,
    peelEdible: true,
    isNew: true,
    description: '**פיתוח ישראלי** מובהק! עגבניות השרי נחשבות להצלחה עולמית בזכות מתיקותן.',
    image: 'https://images.unsplash.com/photo-1590668246398-80452834e8ac?q=80&w=1200',
    varietiesCount: 500,
    famousVarieties: ['סאמר סאן (צהובה)', 'שירן', 'שרי קלאסית'],
    seasonality: 'כל השנה'
  },
  {
    id: 'orange',
    name: 'תפוז',
    scientificName: 'Citrus sinensis',
    group: FruitGroup.Citrus,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'מספר גרעינים לבנים קטנים בתוך הפלחים.',
    hasPeel: true,
    peelEdible: false,
    description: 'ה**תפוז הישראלי**, ובמיוחד מותג ה-Jaffa, הפך לסמל עולמי לאיכות חקלאית.',
    image: 'https://images.unsplash.com/photo-1547514701-42782101795e?q=80&w=1200',
    varietiesCount: 400,
    famousVarieties: ['וושינגטון נבל', 'שמוטי (Jaffa)', 'ולנסיה'],
    seasonality: 'חורף (נובמבר-מרץ)'
  },
  {
    id: 'persimmon',
    name: 'אפרסמון',
    scientificName: 'Diospyros kaki',
    group: FruitGroup.Tropical,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: false,
    pitDescription: 'בזנים הנמכרים בישראל לרוב אין גלעינים.',
    hasPeel: true,
    peelEdible: true,
    description: 'ה**אפרסמון הישראלי** (זן "טריומף") גדל בעיקר בשרון ובשפלה ונאכל כשהוא מוצק ומתוק.',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?q=80&w=1200',
    varietiesCount: 200,
    famousVarieties: ['טריומף (Triumph)', 'פויו (Fuyu)'],
    seasonality: 'סתיו-חורף (אוקטובר-ינואר)'
  },
  {
    id: 'carrot',
    name: 'גזר',
    scientificName: 'Daucus carota',
    group: FruitGroup.Vegetables,
    blessing: BlessingType.Adama,
    canEatRaw: true,
    hasPit: false,
    pitDescription: 'ללא גלעין.',
    hasPeel: true,
    peelEdible: true,
    description: 'ירק שורש חיוני. בישראל מגדלים גזרים בנגב ובצפון, כולל זנים צבעוניים (סגול, צהוב).',
    image: 'https://images.unsplash.com/photo-1598170845058-32b996a66427?q=80&w=1200',
    varietiesCount: 100,
    famousVarieties: ['נאנט', 'שנטני'],
    seasonality: 'כל השנה (שיא בחורף)'
  }
];

export const PRIORITY_VERSE = 'אֶרֶץ חִטָּה וּשְׂעֹרָה וְגֶפֶן וּתְאֵנָה וְרִמּוֹן אֶרֶץ זֵית שֶׁמֶן וּדְבָשׁ';
