
import { Fruit, FruitGroup, BlessingType } from './types';

export const FRUITS: Fruit[] = [
  {
    id: 'wheat',
    name: 'חיטה',
    scientificName: 'Triticum',
    group: FruitGroup.SevenSpecies,
    blessing: BlessingType.Mezonot,
    canEatRaw: false,
    hasPit: false,
    pitDescription: 'ללא גלעין',
    hasPeel: true,
    peelEdible: false,
    priorityOrder: 1,
    description: 'הראשונה ב**שבעת המינים**. בישראל מגדלים זנים מתקדמים כמו **"גליל"** ו**"רותם"** המותאמים לאקלים המקומי. היא הבסיס ללחם ומסמלת שובע וברכה.',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?q=80&w=1200',
    varietiesCount: 20, // Common commercial in Israel
    famousVarieties: ['גליל (ישראלי)', 'רותם', 'חיטת דורום', 'גדרה'],
    seasonality: 'חורף-אביב (קציר באייר-סיון)'
  },
  {
    id: 'barley',
    name: 'שעורה',
    scientificName: 'Hordeum vulgare',
    group: FruitGroup.SevenSpecies,
    blessing: BlessingType.Mezonot,
    canEatRaw: false,
    hasPit: false,
    pitDescription: 'ללא גלעין',
    hasPeel: true,
    peelEdible: false,
    priorityOrder: 2,
    description: 'השנייה ב**שבעת המינים**. השעורה עמידה במיוחד ליובש ומליחות. בישראל פותחו זנים כמו **"עומר"** המצטיינים ביבול גבוה גם בתנאי שחון.',
    image: 'https://images.unsplash.com/photo-1536511132770-e5066804d960?q=80&w=1200',
    varietiesCount: 15,
    famousVarieties: ['עומר (פיתוח ישראלי)', 'שעורה דו-טורית', 'שעורה שש-טורית'],
    seasonality: 'חורף-אביב (קציר מוקדם)'
  },
  {
    id: 'apple',
    name: 'תפוח',
    scientificName: 'Malus domestica',
    group: FruitGroup.StoneFruit,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'זרעים קטנים וכהים בתוך ליבת הפרי.',
    hasPeel: true,
    peelEdible: true,
    description: 'התפוח הישראלי פורח בעיקר בגליל ובגולן. זן ה**"אנה"** הוא פיתוח ישראלי מהפכני שמאפשר גידול תפוחים גם באזורים חמים ללא צורך במנות קור רבות.',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6bcd6?q=80&w=1200',
    varietiesCount: 15,
    famousVarieties: ['אנה (פיתוח ישראלי)', 'פינק ליידי', 'גרני סמית', 'גאלה', 'יונתן'],
    seasonality: 'קיץ-סתיו'
  },
  {
    id: 'banana',
    name: 'בננה',
    scientificName: 'Musa',
    group: FruitGroup.Tropical,
    blessing: BlessingType.Adama,
    canEatRaw: true,
    hasPit: false,
    pitDescription: 'ללא גלעינים משמעותיים.',
    hasPeel: true,
    peelEdible: false,
    description: 'הבננה הישראלית גדלה תחת רשתות בחוף הכרמל ובעמק הירדן. הזן **"זיו"** הוא סלקציה מקומית המותאמת לתנאי הארץ ומניבה פרי איכותי.',
    image: 'https://images.unsplash.com/photo-1571771894821-ad99026a09b7?q=80&w=1200',
    varietiesCount: 5,
    famousVarieties: ['זיו (סלקציה ישראלית)', 'גרנד ניין', 'ויליאמס'],
    seasonality: 'כל השנה'
  },
  {
    id: 'mango',
    name: 'מנגו',
    scientificName: 'Mangifera indica',
    group: FruitGroup.Tropical,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'גלעין גדול ושטוח במרכז.',
    hasPeel: true,
    peelEdible: false,
    description: 'ישראל היא מעצמת מנגו. זן ה**"מאיה"** הישראלי נחשב לאחד הטעימים בעולם בזכות מתיקותו ומרקמו ללא סיבים. גם זן ה**"שלי"** הוא פיתוח מקומי מוצלח.',
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?q=80&w=1200',
    varietiesCount: 12,
    famousVarieties: ['מאיה (פיתוח ישראלי)', 'שלי (פיתוח ישראלי)', 'קיט', 'טומי'],
    seasonality: 'קיץ (יולי-ספטמבר)'
  },
  {
    id: 'watermelon',
    name: 'אבטיח',
    scientificName: 'Citrullus lanatus',
    group: FruitGroup.Melons,
    blessing: BlessingType.Adama,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'זרעים רבים (בזנים מודרניים הם זעירים או חסרים).',
    hasPeel: true,
    peelEdible: false,
    description: 'האבטיח הישראלי עבר מהפכה - מהזנים הגדולים עם הגרעינים כמו **"מללי"** הנוסטלגי, לאבטיחים אישיים וללא גרעינים שמהווים להיט ייצוא.',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?q=80&w=1200',
    varietiesCount: 8,
    famousVarieties: ['מללי (קלאסי ישראלי)', 'אורי (ללא גרעינים)', 'פאשיניישן'],
    seasonality: 'קיץ (מאי-אוגוסט)'
  },
  {
    id: 'melon',
    name: 'מלון',
    scientificName: 'Cucumis melo',
    group: FruitGroup.Melons,
    blessing: BlessingType.Adama,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'זרעים מרוכזים במרכז החלול.',
    hasPeel: true,
    peelEdible: false,
    description: 'מלון ה**"גליה"** הוא אחד מסיפורי ההצלחה הגדולים של החקלאות הישראלית בעולם. הוא פותח במכון וולקני וקרוי על שם בתו של המפתח.',
    image: 'https://images.unsplash.com/photo-1571575173749-bef869f82367?q=80&w=1200',
    varietiesCount: 10,
    famousVarieties: ['גליה (פיתוח ישראלי)', 'ערבה', 'קנטלופ', 'אננס'],
    seasonality: 'קיץ'
  },
  {
    id: 'olive',
    name: 'זית',
    scientificName: 'Olea europaea',
    group: FruitGroup.SevenSpecies,
    blessing: BlessingType.Etz,
    canEatRaw: false,
    hasPit: true,
    pitDescription: 'גלעין קשיח יחיד.',
    hasPeel: true,
    peelEdible: true,
    priorityOrder: 3,
    description: 'הזית הוא סמל ארץ ישראל. זן ה**"ברנע"** שפותח בישראל נחשב לאחד הזנים הטובים בעולם להפקת שמן זית איכותי בזכות עמידותו ופוריותו.',
    image: 'https://images.unsplash.com/photo-1541530531070-449e7939103c?q=80&w=1200',
    varietiesCount: 10,
    famousVarieties: ['ברנע (פיתוח ישראלי)', 'סורי', 'נבאלי', 'פיקואל', 'קורנייקי'],
    seasonality: 'סתיו (מסיק)'
  },
  {
    id: 'date',
    name: 'תמר',
    scientificName: 'Phoenix dactylifera',
    group: FruitGroup.SevenSpecies,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'גלעין מוארך וקשיח.',
    hasPeel: true,
    peelEdible: true,
    priorityOrder: 4,
    description: 'ישראל היא היצואנית המובילה בעולם של תמר ה**"מג\'הול"** המכונה "מלך התמרים". התמרים הישראלים מהערבה ובקעת הירדן נחשבים לאיכותיים ביותר.',
    image: 'https://images.unsplash.com/photo-1571221715431-7b567a14e101?q=80&w=1200',
    varietiesCount: 9,
    famousVarieties: ["מג'הול (מלך התמרים)", "ברהי (צהוב)", "דקל נור", "חיאני"],
    seasonality: 'סתיו'
  },
  {
    id: 'grape',
    name: 'ענב',
    scientificName: 'Vitis vinifera',
    group: FruitGroup.SevenSpecies,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'חרצנים קטנים (או ללא חרצנים בזנים מודרניים).',
    hasPeel: true,
    peelEdible: true,
    priorityOrder: 5,
    description: 'ענבי המאכל הישראלים, כמו ה**"סופריור"**, הם פרי פיתוח מקומי שהפך להצלחה עולמית בזכות היותם ללא חרצנים, פריכים ומתוקים.',
    image: 'https://images.unsplash.com/photo-1537640538966-79f369b41e8f?q=80&w=1200',
    varietiesCount: 20,
    famousVarieties: ['סופריור (פיתוח ישראלי)', 'תומפסון', 'קרימסון', 'מוסקט'],
    seasonality: 'קיץ'
  },
  {
    id: 'avocado',
    name: 'אבוקדו',
    scientificName: 'Persea americana',
    group: FruitGroup.Tropical,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'גלעין אחד ענקי במרכז.',
    hasPeel: true,
    peelEdible: false,
    description: 'האבוקדו הישראלי הוא מותג ייצוא חזק. זן ה**"אטינגר"** פותח בישראל ומתאפיין בקליפה ירוקה חלקה וטעם אגוזי עשיר.',
    image: 'https://images.unsplash.com/photo-1523049673857-d11dd310095c?q=80&w=1200',
    varietiesCount: 6,
    famousVarieties: ['אטינגר (פיתוח ישראלי)', 'האס (Hass)', 'פוארטה', 'ריד'],
    seasonality: 'חורף-אביב'
  },
  {
    id: 'mandarin',
    name: 'מנדרינה (אור)',
    scientificName: 'Citrus reticulata',
    group: FruitGroup.Citrus,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: false,
    pitDescription: 'בדרך כלל ללא זרעים.',
    hasPeel: true,
    peelEdible: false,
    description: 'המנדרינה מזן **"אור"** היא פאר היצירה של החקלאות הישראלית. היא פותחה במכון וולקני ונחשבת למנדרינה הטובה והמבוקשת בעולם בזכות מתיקותה וקלות הקילוף.',
    image: 'https://images.unsplash.com/photo-1557800636-894a64c1696f?q=80&w=1200',
    varietiesCount: 10,
    famousVarieties: ['אור (פיתוח ישראלי)', 'מורקוט', 'מיכל', 'סנצומא'],
    seasonality: 'חורף (ינואר-אפריל)'
  },
  {
    id: 'persimmon',
    name: 'אפרסמון',
    scientificName: 'Diospyros kaki',
    group: FruitGroup.Tropical,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: false,
    pitDescription: 'בזן הישראלי אין גלעינים.',
    hasPeel: true,
    peelEdible: true,
    description: 'האפרסמון הישראלי מזן **"טריומף"** עובר תהליך ייחודי להוצאת העפיצות, מה שהופך אותו לאחד הפירות המתוקים והאהובים ביותר בחורף.',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?q=80&w=1200',
    varietiesCount: 3,
    famousVarieties: ['טריומף (הזן המוביל בישראל)', 'פויו'],
    seasonality: 'סתיו-חורף'
  },
  {
    id: 'strawberry',
    name: 'תות שדה',
    scientificName: 'Fragaria',
    group: FruitGroup.Forest,
    blessing: BlessingType.Adama,
    canEatRaw: true,
    hasPit: false,
    pitDescription: 'זרעים קטנים על פני הקליפה.',
    hasPeel: false,
    peelEdible: true,
    description: 'בישראל פותחו זני תותים מעולים כמו **"אורלי"** ו**"תמר"** המצטיינים בעמידות, גודל ומתיקות גבוהה גם בימי החורף הקרים.',
    image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?q=80&w=1200',
    varietiesCount: 12,
    famousVarieties: ['אורלי (פיתוח ישראלי)', 'תמר (פיתוח ישראלי)', 'מלאך', 'יובל'],
    seasonality: 'חורף-אביב'
  },
  {
    id: 'cherry_tomato',
    name: 'עגבניית שרי',
    scientificName: 'Solanum lycopersicum',
    group: FruitGroup.ExoticVegetables,
    blessing: BlessingType.Adama,
    canEatRaw: true,
    hasPit: false,
    pitDescription: 'זרעים רכים הנאכלים.',
    hasPeel: false,
    peelEdible: true,
    isNew: true,
    description: 'המצאה ישראלית גאה! עגבניות השרי פותחו באוניברסיטה העברית והפכו ללהיט עולמי. זנים כמו **"סאמר סאן"** הצהובה נחשבים למתוקים ביותר.',
    image: 'https://images.unsplash.com/photo-1590668246398-80452834e8ac?q=80&w=1200',
    varietiesCount: 50,
    famousVarieties: ['סאמר סאן (צהובה)', 'שירן', 'שוקולו', 'שרי קלאסית'],
    seasonality: 'כל השנה'
  },
  {
    id: 'orange',
    name: 'תפוז (שמוטי)',
    scientificName: 'Citrus sinensis',
    group: FruitGroup.Citrus,
    blessing: BlessingType.Etz,
    canEatRaw: true,
    hasPit: true,
    pitDescription: 'זרעים לבנים קטנים.',
    hasPeel: true,
    peelEdible: false,
    description: 'התפוז מזן **"שמוטי"** (המוכר כ-Jaffa Orange) הוא המותג החקלאי הישראלי המפורסם ביותר היסטורית, בזכות צורתו האובלית וטעמו הייחודי.',
    image: 'https://images.unsplash.com/photo-1547514701-42782101795e?q=80&w=1200',
    varietiesCount: 10,
    famousVarieties: ['שמוטי (Jaffa)', 'וושינגטון נבל', 'ולנסיה', 'טבורי'],
    seasonality: 'חורף'
  }
];

export const PRIORITY_VERSE = 'אֶרֶץ חִטָּה וּשְׂעֹרָה וְגֶפֶן וּתְאֵנָה וְרִמּוֹן אֶרֶץ זֵית שֶׁמֶן וּדְבָשׁ';
